# @format

name: flutter_x_widgets
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  cupertino_date_time_picker_loki: ^0.0.3
  table_calendar: ^3.1.3
  forge2d: ^0.11.0
  intl: ^0.20.2
  shared_preferences: ^2.5.1
  math_expressions: ^2.6.0
  flutter_3d_controller: ^2.1.0
  equatable: ^2.0.7
  flutter_shaders: ^0.1.3
  google_fonts:
  flutter_animate:
  just_waveform: ^0.0.7
  just_audio: ^0.9.40
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  shaders:
    - shaders/impeller.frag
  assets:
    - assets/images/graph.png
    - assets/images/
    - assets/3d_numbers/
    - assets/audio/
  fonts:
    - family: NeumaticGothic-Black
      fonts:
        - asset: assets/fonts/NeumaticGothic-Black.ttf
    - family: NeumaticGothic-SemiBold
      fonts:
        - asset: assets/fonts/NeumaticGothic-SemiBold.ttf
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
